/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankproject;
import java.awt.*;
import java.awt.event.*;
import java.math.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sudha
 */
public class Homepageuser extends javax.swing.JFrame {

    /**
     * Creates new form homepageuse
     */
    public Homepageuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        accdet = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO MO BANK");

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check Balance");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        accdet.setBackground(new java.awt.Color(255, 153, 0));
        accdet.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        accdet.setForeground(new java.awt.Color(255, 255, 255));
        accdet.setText("Account Details");
        accdet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accdetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accdetMouseEntered(evt);
            }
        });
        accdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accdetActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Transfer Money");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Apply for a Loan");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Transaction History");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 51, 255));
        jButton6.setFont(new java.awt.Font("Keraleeyam", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 255, 0));
        jButton6.setText("Savings Account");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Want to Save Money?");

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Deposit Money");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 204, 0));
        jButton7.setFont(new java.awt.Font("Dyuthi", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Logout");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 153, 0));
        jButton8.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Withdraw Money");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(accdet, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accdet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void accdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accdetMouseClicked
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_info","root","Omnamo@245");
            Statement stmt = con.createStatement(); 
            String query = "select * from users where Username = '"+GetDetails.Username+"' ";
            ResultSet rs = stmt.executeQuery(query);
            
            if(rs.next()){
                String Name = rs.getString("Name");
                String Username = rs.getString("Username");
                String Phone = rs.getString("Phone");
                String Email = rs.getString("Email");
                
                        
                JLabel label = new JLabel("<html><b>Name:</b> " + Name + "<br><b>Username:</b> " + Username + "<br><b>Phone:</b> " + Phone + "<br><b>Email:</b> " + Email  + "</html>");
                label.setFont(new Font("Segoe UI", Font.PLAIN, 20));
                JFrame frame = new JFrame("User Details");
                label.setHorizontalAlignment(SwingConstants.CENTER);
                frame.getContentPane().add(label);
                frame.setSize(250, 250);
                frame.setVisible(true);
                        
            }
            else{
                JOptionPane.showMessageDialog(null, "User not found!");
            }
                                    
        }
        catch(Exception e){
            System.out.println(e);
        }
               
    }//GEN-LAST:event_accdetMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_info","root","Omnamo@245");
            Statement stmt = con.createStatement(); 
            String query = "select * from users where Username = '"+GetDetails.Username+"' ";
            ResultSet rs = stmt.executeQuery(query);
                    
            if(rs.next()){
                GetDetails.amount = new BigInteger(rs.getString("Amount"));
                     
                JFrame textframe = new JFrame("Loan");
                JLabel Info = new JLabel("Enter the loan amount:");
                JButton takeLoan = new JButton("Take Loan");
                JLabel loanInfo = new JLabel("<html>Conditions of the loan are:<br/>1. The interest rate is 5%<br/>2. The time period to pay back the amount is 5 years</html>");
                JTextField textfield = new JTextField(16);
                
                Font font = new Font("Serif", Font.BOLD, 15);
                textfield.setFont(font);

                JPanel p = new JPanel();
                p.add(Info);
                p.add(textfield);
                p.add(takeLoan);
                p.add(loanInfo);

                textframe.add(p);
                textframe.setSize(600, 200);
                textframe.show();
                
                takeLoan.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        try {
                            GetDetails.loanAmount = new BigInteger(textfield.getText());
                            BigInteger Zero = BigInteger.valueOf(0);
                            
                            if (GetDetails.loanAmount.compareTo(Zero) < 0) {
                                throw new Exception();
                            }
                            
                            if (rs.getInt("LoanTaken") == 1) {
                                JOptionPane.showMessageDialog(null, "You already have a pending loan!");
                            }
                            else {
                                GetDetails.amount = GetDetails.amount.add(GetDetails.loanAmount);
                                GetDetails.loanTaken = 1;
                                
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_info","root","Omnamo@245");
                                Statement stmt = con.createStatement(); 
                                String query2 = " UPDATE users SET Amount = " + GetDetails.amount + " WHERE Username = '" + GetDetails.Username + "' ";
                                String query3 = " UPDATE users SET LoanTaken = " + GetDetails.loanTaken + " WHERE Username = '" + GetDetails.Username + "' ";
                                String query4 = " UPDATE users SET LoanAmount = " + GetDetails.loanAmount + " WHERE Username = '" + GetDetails.Username + "' ";
                                PreparedStatement preparedStmt1 = con.prepareStatement(query2);
                                PreparedStatement preparedStmt2 = con.prepareStatement(query3);
                                PreparedStatement preparedStmt3 = con.prepareStatement(query4);
                                preparedStmt1.executeUpdate();
                                preparedStmt2.executeUpdate();
                                preparedStmt3.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Congratulations! Loan Approved");

                                textframe.show(false);
                            }
                        }
                        catch(Exception ee) {
                            GetDetails.loanTaken = 0;
                            JOptionPane.showMessageDialog(null, "Please enter a valid amount!");
                        }
                    }
                });
    
            }
            else{
                JOptionPane.showMessageDialog(null, "User not found!");
            }
                                    
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void accdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accdetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accdetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:                   
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_info","root","Omnamo@245");
            Statement stmt = con.createStatement(); 
            String query = "select * from users where Username = '"+GetDetails.Username+"' ";
            ResultSet rs = stmt.executeQuery(query);
                    
            if(rs.next()){
                BigInteger Amount = new BigInteger(rs.getString("Amount"));
                        
                JLabel label = new JLabel("<html><b>Your balance (in INR): ₹</b> " + Amount + "</html>");
                label.setFont(new Font("Segoe UI", Font.PLAIN, 20));
                JFrame frame = new JFrame("Account Balance");
                label.setHorizontalAlignment(SwingConstants.CENTER);
                frame.getContentPane().add(label);
                frame.setSize(600, 100);
                frame.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "User not found!");
            }
                                    
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_info","root","Omnamo@245");
               Statement stmt = con.createStatement(); 
               ResultSet rs1 = stmt.executeQuery("select count(*) from transhistory");
               String uname =  GetDetails.Username;
               ResultSet rs = stmt.executeQuery("SELECT * FROM transhistory WHERE Username = '"+GetDetails.Username+"'");
               
               String[] columnNames = {"transType","Username","transAmnt","finalAmnt"};
               Object[][] rowdata = new Object[100][4];
               
               int row = 0;
               while(rs.next()){
                   
                        rowdata[row][0] = rs.getString("transType");
                        rowdata[row][1] = rs.getString("Username");
                        rowdata[row][2] = rs.getString("transAmnt");
                        rowdata[row][3] = rs.getString("finalAmnt");
                        
                        row++;
               }
               
               JTable table = new JTable(rowdata, columnNames);
               JScrollPane scrollPane = new JScrollPane(table);
               JFrame frame = new JFrame("transHistory");
               frame.add(scrollPane);
               frame.setSize(400, 300);
               frame.setVisible(true);
               
               con.close();
         }
         catch(Exception e){
            System.out.println(e);
         }
        
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This feature will be added in the next update");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_info","root","Omnamo@245");
            Statement stmt = con.createStatement(); 
            String query = "select * from users where Username = '"+GetDetails.Username+"' ";
            ResultSet rs = stmt.executeQuery(query);
                    
            if(rs.next()){
                GetDetails.amount = new BigInteger(rs.getString("Amount"));
                     
                JFrame textframe = new JFrame("Deposit");
                JButton deposit = new JButton("Deposit Amount");
                JTextField textfield = new JTextField(16);
                
                Font font = new Font("Serif", Font.BOLD, 15);
                textfield.setFont(font);

                JPanel p = new JPanel();
                p.add(textfield);
                p.add(deposit);

                textframe.add(p);
                textframe.setSize(300, 100);
                textframe.show();
                
                deposit.addActionListener(new ActionListener() {
                    
                    public void actionPerformed(ActionEvent e) {
                        try {
                            GetDetails.amountDeposited = new BigInteger(textfield.getText());
                            GetDetails.amount = GetDetails.amount.add(GetDetails.amountDeposited);
                            BigInteger Zero = BigInteger.valueOf(0);
                            if (GetDetails.amountDeposited.compareTo(Zero) < 0) {
                                throw new Exception();
                            }  
                            
                            
                            
                           
                            
                            String query2 = " UPDATE users SET Amount = " + GetDetails.amount + " WHERE Username = '" + GetDetails.Username + "'  ";
                            PreparedStatement preparedStmt = con.prepareStatement(query2);
                            preparedStmt.executeUpdate();
                            
                            
                            
                            
                            
                          String transType = "deposit";
                          String Username = GetDetails.Username;
                          int x = GetDetails.amount.intValue();
                          int y = GetDetails.amountDeposited.intValue();
                            System.out.println(x);
                            System.out.println(transType);
                            System.out.println(Username);
                          String insertQuery = "INSERT INTO transhistory VALUES (?, ?, ?, ?)";
                          PreparedStatement insertStmt = con.prepareStatement(insertQuery);
                          insertStmt.setString(1, transType);
                          insertStmt.setString(2, Username);
                          insertStmt.setInt(3, y);
                          insertStmt.setInt(4, x);
                          insertStmt.executeUpdate();
                          
                            JOptionPane.showMessageDialog(null, "Amount Deposited");
                            textframe.show(false);
                        }
                        catch(Exception ee) {
                            JOptionPane.showMessageDialog(null, "Please enter a valid amount!");
                        }
                        
                        
                        
                    }
                });
    
            }
            else{
                JOptionPane.showMessageDialog(null, "User not found!");
            }
                                    
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(jButton7, "Are you sure?");
        
        if (a == JOptionPane.YES_OPTION) {
            dispose();
            
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void accdetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accdetMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_accdetMouseEntered

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_info","root","Omnamo@245");
            Statement stmt = con.createStatement(); 
            String query = "select * from users where Username = '"+GetDetails.Username+"' ";
            ResultSet rs = stmt.executeQuery(query);
                    
            if(rs.next()){
                GetDetails.amount = new BigInteger(rs.getString("Amount"));
                     
                JFrame textframe = new JFrame("Withdraw");
                JButton deposit = new JButton("Withdraw Amount");
                JTextField textfield = new JTextField(16);
                
                Font font = new Font("Serif", Font.BOLD, 15);
                textfield.setFont(font);

                JPanel p = new JPanel();
                p.add(textfield);
                p.add(deposit);

                textframe.add(p);
                textframe.setSize(300, 100);
                textframe.show();
                
                deposit.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        try {
                            GetDetails.amountDeposited = new BigInteger(textfield.getText());
                            BigInteger Zero = BigInteger.valueOf(0);
                            
                            if (GetDetails.amountDeposited.compareTo(Zero) < 0) {
                                throw new Exception();
                            }
                            
                            if (GetDetails.amount.subtract(GetDetails.amountDeposited).compareTo(Zero) < 0) {
                                JOptionPane.showMessageDialog(null, "You don't have enough money!");
                            }
                            else {
                                GetDetails.amount = GetDetails.amount.subtract(GetDetails.amountDeposited);
                                
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users_info","root","Omnamo@245");
                                Statement stmt = con.createStatement(); 
                                String query2 = " UPDATE users SET Amount = " + GetDetails.amount + " WHERE Username = '" + GetDetails.Username + "' ";
                                PreparedStatement preparedStmt = con.prepareStatement(query2);
                                preparedStmt.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Amount Withdrawn");
                                
                                
                                String transType = "withdraw";
                                String Username = GetDetails.Username;
                                int x = GetDetails.amount.intValue();
                                int y = GetDetails.amountDeposited.intValue();
                                
                                System.out.println(x);
                                System.out.println(y);
                                System.out.println(transType);
                                System.out.println(Username);
                                String insertQuery = "INSERT INTO transhistory VALUES (?, ?, ?, ?)";
                                PreparedStatement insertStmt = con.prepareStatement(insertQuery);
                                insertStmt.setString(1, transType);
                                insertStmt.setString(2, Username);
                                insertStmt.setInt(3, y);
                                insertStmt.setInt(4, x);
                                insertStmt.executeUpdate();
                                
                                
                                

                                textframe.show(false);
                            }
                        }
                        catch(Exception ee) {
                            JOptionPane.showMessageDialog(null, "Please enter a valid amount!");
                        }
                    }
                });
    
            }
            else{
                JOptionPane.showMessageDialog(null, "User not found!");
            }
                                    
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This feature will be added in the next update");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepageuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accdet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class LoanException {

        public LoanException() {
        }
    }
}
